FIX: Use appropriate type in gray matter growing function dim decl
Use appropriate type in gray matter growing function dimensionality
declaration to make it compatible with MATLAB R2026a. Use:
```
const mwSize *dim;
```

instead of:
```
const int *dim;
```

Fixes:
```
mex -O grow_gray.cpp
Building with 'Xcode Clang++'.
Error using mex
In file included from vistasoft/mrAnatomy/MrGray/GrowGrayMatter/grow_gray.cpp:19:
vistasoft/mrAnatomy/MrGray/GrowGrayMatter/grow_gray.cpp:34:12: error: incompatible pointer types
assigning to 'const int *' from 'const mwSize *' (aka 'const unsigned long *')
   34 |     dim  = mxGetDimensions(prhs[0]);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
/Applications/MATLAB_R2026a.app/extern/include/matrix.h:297:25: note: expanded from macro 'mxGetDimensions'
  297 | #define mxGetDimensions mxGetDimensions_730
      |                         ^
2 warnings and 1 error generated.

```